use anyhow::{bail, Context, Result};
use clap::{Args, Parser, Subcommand};
use reqwest::Client;
use serde::Deserialize;
use serde_json::Value;
use std::fmt;

#[derive(Parser, Debug)]
#[command(
    name = "synapse",
    version,
    about = "Synapse CLI",
    long_about = "Interact with a Synapse instance from the command line.\n\nUse the nested subcommands to inspect health, watch events, or run reconciliation commands.",
    arg_required_else_help = true
)]
struct Cli {
    /// Base URL of the Synapse API.
    #[arg(long, env = "SYNAPSE_BASE_URL", default_value = "http://localhost:3000")]
    base_url: String,

    /// API key for authentication.
    #[arg(long, env = "SYNAPSE_API_KEY", default_value = "")]
    api_key: String,

    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand, Debug)]
enum Commands {
    /// Admin operations exposed by the Synapse API.
    #[command(subcommand)]
    Admin(AdminCommands),

    /// Event stream commands.
    #[command(subcommand)]
    Events(EventsCommands),
}

#[derive(Subcommand, Debug)]
enum AdminCommands {
    /// Reconciliation reports and runs.
    #[command(subcommand)]
    Reconciliation(ReconciliationCommands),
}

#[derive(Subcommand, Debug)]
enum ReconciliationCommands {
    #[command(
        about = "List reconciliation reports",
        long_about = "List reconciliation reports generated by the admin API.\n\nRequired flags: none.\nOptional flags:\n  --limit <LIMIT>   Maximum number of reports to return (default: 20).\n  --offset <OFFSET> Number of reports to skip before returning results (default: 0).\n  --json            Print the raw API response as JSON."
    )]
    Reports {
        /// Maximum number of reports to return.
        #[arg(long, value_name = "LIMIT", default_value_t = 20)]
        limit: u32,

        /// Number of reports to skip before returning results.
        #[arg(long, value_name = "OFFSET", default_value_t = 0)]
        offset: u32,

        /// Print the raw API response as JSON.
        #[arg(long)]
        json: bool,
    },

    #[command(
        about = "Show a reconciliation report",
        long_about = "Fetch one reconciliation report by UUID and print the full response body.\n\nRequired flags:\n  <REPORT_ID>       UUID of the report to fetch.\nOptional flags:\n  --json            Print the raw API response as JSON."
    )]
    Report {
        /// UUID of the reconciliation report to fetch.
        #[arg(value_name = "REPORT_ID")]
        report_id: String,

        /// Print the raw API response as JSON.
        #[arg(long)]
        json: bool,
    },

    #[command(
        about = "Run a reconciliation report",
        long_about = "Run a reconciliation pass for one Stellar account and persist the result.\n\nRequired flags:\n  --account <ACCOUNT>      Stellar account to reconcile.\nOptional flags:\n  --period-hours <HOURS>   Hours of history to include (default: 24).\n  --json                   Print the raw API response as JSON."
    )]
    Run {
        /// Stellar account to reconcile.
        #[arg(long, value_name = "ACCOUNT")]
        account: String,

        /// Hours of history to include.
        #[arg(long, value_name = "HOURS")]
        period_hours: Option<u32>,

        /// Print the raw API response as JSON.
        #[arg(long)]
        json: bool,
    },
}

#[derive(Subcommand, Debug)]
enum EventsCommands {
    #[command(
        about = "Watch transaction status events",
        long_about = "Watch transaction status updates emitted by the Synapse API.\n\nRequired flags:\n  --token <TOKEN>      Authentication token used to open the event stream.\nOptional flags:\n  --limit <LIMIT>       Maximum number of events to print before exiting (default: 5).\n  --json                Print each event as JSON instead of a human-readable line."
    )]
    Watch(WatchArgs),
}

#[derive(Args, Debug)]
struct WatchArgs {
    /// Required: authentication token used to open the event stream.
    #[arg(long, value_name = "TOKEN")]
    token: String,

    /// Optional: maximum number of events to print before exiting (default: 5).
    #[arg(long, value_name = "LIMIT", default_value_t = 5)]
    limit: usize,

    /// Optional: print each event as JSON instead of a human-readable line.
    #[arg(long)]
    json: bool,
}

#[derive(Debug, Deserialize)]
struct RunResponse {
    message: String,
    report: ReportSummary,
}

#[derive(Debug, Deserialize)]
struct ReportSummary {
    id: String,
    generated_at: String,
    period_start: String,
    period_end: String,
    total_db_transactions: i64,
    total_chain_payments: i64,
    missing_on_chain_count: i64,
    orphaned_payments_count: i64,
    amount_mismatches_count: i64,
    has_discrepancies: bool,
}

#[derive(Debug, Deserialize)]
struct ListReportsResponse {
    reports: Vec<ReportSummary>,
    total: i64,
    limit: i32,
    offset: i32,
}

#[tokio::main]
async fn main() -> Result<()> {
    let cli = Cli::parse();
    let client = Client::new();
    let base_url = cli.base_url.trim_end_matches('/');

    match cli.command {
        Commands::Admin(AdminCommands::Reconciliation(command)) => {
            handle_reconciliation(&client, base_url, command).await?;
        }
        Commands::Events(EventsCommands::Watch(args)) => {
            handle_events_watch(&client, base_url, &cli.api_key, args).await?;
        }
    }

    Ok(())
}

async fn handle_reconciliation(client: &Client, base_url: &str, command: ReconciliationCommands) -> Result<()> {
    match command {
        ReconciliationCommands::Reports { limit, offset, json } => {
            let url = format!("{base_url}/admin/reconciliation/reports?limit={limit}&offset={offset}");
            let response = send_json_request::<ListReportsResponse>(client, &url).await?;
            if json {
                println!("{}", serde_json::to_string_pretty(&response)?);
            } else {
                println!("Reports: {} total", response.total);
                println!("ID | Generated | Period Start | Discrepancies");
                for report in response.reports {
                    println!(
                        "{} | {} | {} | {}",
                        report.id,
                        report.generated_at,
                        report.period_start,
                        if report.has_discrepancies { "yes" } else { "no" }
                    );
                }
            }
        }
        ReconciliationCommands::Report { report_id, json } => {
            let url = format!("{base_url}/admin/reconciliation/reports/{report_id}");
            let response = send_json_request::<Value>(client, &url).await?;
            if json {
                println!("{}", serde_json::to_string_pretty(&response)?);
            } else {
                println!("Report ID: {}", response["id"].as_str().unwrap_or("unknown"));
                println!("Summary:");
                println!(
                    "  Database transactions: {}",
                    response["summary"]["total_db_transactions"]
                );
                println!(
                    "  Has discrepancies: {}",
                    if response["summary"]["has_discrepancies"].as_bool().unwrap_or(false) {
                        "yes"
                    } else {
                        "no"
                    }
                );
            }
        }
        ReconciliationCommands::Run { account, period_hours, json } => {
            let body = serde_json::json!({
                "account": account,
                "period_hours": period_hours,
            });
            let response = send_json_request::<RunResponse>(client, &format!("{base_url}/admin/reconciliation/run"))
                .await
                .with_context(|| "failed to run reconciliation")?;
            let response_body = serde_json::to_value(response)?;
            if json {
                println!("{}", serde_json::to_string_pretty(&response_body)?);
            } else {
                println!("Reconciliation completed successfully");
                println!("Database transactions: {}", response_body["report"]["total_db_transactions"]);
                println!(
                    "Has discrepancies: {}",
                    if response_body["report"]["has_discrepancies"].as_bool().unwrap_or(false) {
                        "yes"
                    } else {
                        "no"
                    }
                );
            }
        }
    }

    Ok(())
}

async fn send_json_request<T: serde::de::DeserializeOwned>(client: &Client, url: &str) -> Result<T> {
    let response = client.get(url).send().await.context("request failed")?;
    if !response.status().is_success() {
        let body = response.text().await.unwrap_or_default();
        bail!("server returned {}: {}", response.status(), body);
    }

    response.json::<T>().await.context("failed to parse JSON response")
}

async fn handle_events_watch(client: &Client, base_url: &str, api_key: &str, args: WatchArgs) -> Result<()> {
    let url = format!(
        "{}/events/watch?token={}&limit={}",
        base_url.trim_end_matches('/'),
        percent_encode(&args.token),
        args.limit
    );

    let mut request = client.get(&url);
    if !api_key.is_empty() {
        request = request.header("X-API-Key", api_key);
    }

    let response = request.send().await.context("failed to connect to event stream")?;
    if !response.status().is_success() {
        let body = response.text().await.unwrap_or_default();
        bail!("event stream request failed with {}: {}", response.status(), body);
    }

    let body = response.text().await.context("failed to read event stream payload")?;
    let events: Value = serde_json::from_str(&body).context("failed to parse event stream payload")?;

    if args.json {
        println!("{}", serde_json::to_string_pretty(&events)?);
        return Ok(());
    }

    match events {
        Value::Array(items) => {
            for item in items.iter().take(args.limit) {
                let transaction_id = item["transaction_id"].as_str().unwrap_or("unknown");
                let status = item["status"].as_str().unwrap_or("unknown");
                let timestamp = item["timestamp"].as_str().unwrap_or("unknown");
                let message = item["message"].as_str().unwrap_or("");
                if message.is_empty() {
                    println!("{transaction_id} | {status} | {timestamp}");
                } else {
                    println!("{transaction_id} | {status} | {timestamp} | {message}");
                }
            }
        }
        Value::Object(_) => println!("{}", serde_json::to_string_pretty(&events)?),
        _ => println!("{events}"),
    }

    Ok(())
}

fn percent_encode(value: &str) -> String {
    urlencoding::encode(value).into_owned()
}

impl fmt::Display for RunResponse {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.message)
    }
}
