use anyhow::{bail, Context, Result};
use clap::{Parser, Subcommand};
use serde::{Deserialize, Serialize};
use serde_json::json;
use uuid::Uuid;

mod formatter;
mod output;

use formatter::{Formatter, OutputFormat};

#[derive(Parser, Debug)]
#[command(name = "synapse", version, about = "Synapse CLI")]
struct Cli {
    /// Base URL of the Synapse API.
    #[arg(
        long = "base-url",
        alias = "url",
        env = "SYNAPSE_BASE_URL",
        default_value = "http://127.0.0.1:3000"
    )]
    base_url: String,

    /// API key for authenticated requests.
    #[arg(long, env = "SYNAPSE_API_KEY", default_value = "")]
    api_key: String,

    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand, Debug)]
enum Commands {
    /// Admin operations.
    #[command(subcommand)]
    Admin(AdminCommands),

    /// Transaction commands.
    #[command(subcommand)]
    Transactions(TransactionsCommands),

    /// Settlement commands.
    #[command(subcommand)]
    Settlements(SettlementsCommands),

    /// Generate shell completion scripts.
    Completions {
        /// Shell to generate completions for: bash, zsh, or fish.
        shell: String,
    },
}

#[derive(Subcommand, Debug)]
enum AdminCommands {
    /// Reconciliation reports and runs.
    #[command(subcommand)]
    Reconciliation(ReconciliationCommands),

    /// Distributed lock administration.
    #[command(subcommand)]
    Locks(LockCommands),

    /// Tenant quota administration.
    #[command(subcommand)]
    Quotas(QuotaCommands),
}

#[derive(Subcommand, Debug)]
enum LockCommands {
    #[command(
        about = "List active distributed locks",
        long_about = "List active distributed locks currently held by this Synapse instance.\n\nRequired flags: none.\nOptional flags:\n  --json            Print the raw API response as pretty JSON instead of the default table.\n\nOutput fields:\n  resource          Protected resource name for the lock.\n  token             Lock owner token.\n  acquired_at       Unix timestamp, in seconds, when the lock was acquired.\n  ttl_secs          Lock TTL in seconds.\n  expected_duration_secs  Expected lock hold duration in seconds.\n  overdue           Whether the lock has exceeded twice its expected duration."
    )]
    List {
        /// Print the raw API response as JSON.
        #[arg(long)]
        json: bool,
    },
}

#[derive(Subcommand, Debug)]
enum QuotaCommands {
    /// List quota usage for all active tenants.
    List {
        /// Print the raw API response as JSON.
        #[arg(long)]
        json: bool,
    },

    /// Get quota usage for one tenant.
    Get {
        /// Tenant UUID.
        tenant_id: Uuid,

        /// Print the raw API response as JSON.
        #[arg(long)]
        json: bool,
    },

    /// Set a tenant quota override.
    Set {
        /// Tenant UUID.
        tenant_id: Uuid,

        /// Positive quota limit.
        #[arg(value_name = "LIMIT", conflicts_with = "limit_flag")]
        limit: Option<u32>,

        /// Positive quota limit.
        #[arg(long = "limit", value_name = "LIMIT")]
        limit_flag: Option<u32>,

        /// Print the raw API response as JSON.
        #[arg(long)]
        json: bool,
    },

    /// Reset the current usage counter for one tenant.
    Reset {
        /// Tenant UUID.
        tenant_id: Uuid,

        /// Print the raw API response as JSON.
        #[arg(long)]
        json: bool,
    },
}

#[derive(Subcommand, Debug)]
enum ReconciliationCommands {
    #[command(
        about = "List reconciliation reports",
        long_about = "List reconciliation reports generated by the admin API.\n\nRequired flags: none.\nOptional flags:\n  --limit <LIMIT>   Maximum number of reports to return (default: 20).\n  --offset <OFFSET>  Number of reports to skip before returning results (default: 0).\n  --json            Print the raw API response as JSON."
    )]
    Reports {
        #[arg(long, value_name = "LIMIT", default_value_t = 20)]
        limit: u32,

        #[arg(long, value_name = "OFFSET", default_value_t = 0)]
        offset: u32,

        #[arg(long)]
        json: bool,
    },

    #[command(
        about = "Show a reconciliation report",
        long_about = "Fetch one reconciliation report by UUID and print the full response body.\n\nRequired flags:\n  <REPORT_ID>       UUID of the report to fetch.\nOptional flags:\n  --json            Print the raw API response as JSON."
    )]
    Report {
        #[arg(value_name = "REPORT_ID")]
        report_id: Uuid,

        #[arg(long)]
        json: bool,
    },

    #[command(
        about = "Run a reconciliation report",
        long_about = "Run a reconciliation pass for one Stellar account and persist the result.\n\nRequired flags:\n  --account <ACCOUNT>      Stellar account to reconcile.\nOptional flags:\n  --period-hours <HOURS>   Hours of history to include (default: 24).\n  --json                   Print the raw API response as JSON."
    )]
    Run {
        #[arg(long, value_name = "ACCOUNT")]
        account: String,

        #[arg(long, value_name = "HOURS", default_value_t = 24)]
        period_hours: u32,

        #[arg(long)]
        json: bool,
    },
}

#[derive(Subcommand, Debug)]
enum TransactionsCommands {
    /// Export transactions to CSV or JSON format with optional filters.
    Export {
        /// Export format: csv or json.
        #[arg(long, default_value = "csv")]
        format: String,

        /// Start date filter, inclusive, in YYYY-MM-DD format.
        #[arg(long)]
        from: Option<String>,

        /// End date filter, inclusive, in YYYY-MM-DD format.
        #[arg(long)]
        to: Option<String>,

        /// Filter by transaction status.
        #[arg(long)]
        status: Option<String>,

        /// Filter by asset code.
        #[arg(long)]
        asset_code: Option<String>,

        /// Save output to a file instead of stdout.
        #[arg(long)]
        output: Option<String>,
    },
}

#[derive(Subcommand, Debug)]
enum SettlementsCommands {
    /// List settlements with cursor-based pagination.
    List {
        #[arg(long)]
        cursor: Option<String>,

        #[arg(long, default_value_t = 10)]
        limit: i64,

        #[arg(long, default_value = "forward")]
        direction: String,

        #[arg(long, default_value = "table")]
        format: String,
    },

    /// Get a specific settlement by ID.
    Get {
        settlement_id: String,

        #[arg(long, default_value = "table")]
        format: String,
    },
}

#[derive(Debug, Deserialize, Serialize)]
struct TenantQuotaView {
    tenant_id: Uuid,
    name: String,
    rate_limit_per_minute: i32,
    quota_status: Option<serde_json::Value>,
}

#[derive(Debug, Deserialize, Serialize)]
struct ListLocksResponse {
    active_locks: Vec<ActiveLockView>,
    total: usize,
    overdue: usize,
}

#[derive(Debug, Deserialize, Serialize)]
struct ActiveLockView {
    resource: String,
    token: String,
    acquired_at: u64,
    ttl_secs: u64,
    expected_duration_secs: u64,
    overdue: bool,
}

#[derive(Debug, Deserialize, Serialize)]
struct ListReportsResponse {
    reports: Vec<ReportSummary>,
    total: i64,
    limit: i32,
    offset: i32,
}

#[derive(Debug, Deserialize, Serialize)]
struct ReportSummary {
    id: Uuid,
    generated_at: String,
    period_start: String,
    period_end: String,
    total_db_transactions: i32,
    total_chain_payments: i32,
    missing_on_chain_count: i32,
    orphaned_payments_count: i32,
    amount_mismatches_count: i32,
    has_discrepancies: bool,
}

#[derive(Debug, Deserialize, Serialize)]
struct ReportDetailResponse {
    id: Uuid,
    generated_at: String,
    period_start: String,
    period_end: String,
    summary: ReportDetailSummary,
    missing_on_chain: Vec<serde_json::Value>,
    orphaned_payments: Vec<serde_json::Value>,
    amount_mismatches: Vec<serde_json::Value>,
}

#[derive(Debug, Deserialize, Serialize)]
struct ReportDetailSummary {
    total_db_transactions: usize,
    total_chain_payments: usize,
    missing_on_chain_count: i32,
    orphaned_payments_count: i32,
    amount_mismatches_count: i32,
    has_discrepancies: bool,
}

#[derive(Debug, Deserialize, Serialize)]
struct RunResponse {
    message: String,
    report: ReportSummary,
}

#[derive(Debug, Serialize)]
struct RunRequest<'a> {
    account: &'a str,
    period_hours: Option<u32>,
}

struct ApiClient {
    http: reqwest::Client,
    base_url: String,
    api_key: String,
}

impl ApiClient {
    fn new(base_url: String, api_key: String) -> Self {
        Self {
            http: reqwest::Client::new(),
            base_url: base_url.trim_end_matches('/').to_string(),
            api_key,
        }
    }

    async fn get<T>(&self, path: &str) -> Result<T>
    where
        T: for<'de> Deserialize<'de>,
    {
        self.send(self.http.get(self.url(path))).await
    }

    async fn put_json<T>(&self, path: &str, body: serde_json::Value) -> Result<T>
    where
        T: for<'de> Deserialize<'de>,
    {
        self.send(self.http.put(self.url(path)).json(&body)).await
    }

    async fn post_json<T, B>(&self, path: &str, body: &B) -> Result<T>
    where
        T: for<'de> Deserialize<'de>,
        B: Serialize + ?Sized,
    {
        self.send(self.http.post(self.url(path)).json(body)).await
    }

    async fn delete<T>(&self, path: &str) -> Result<T>
    where
        T: for<'de> Deserialize<'de>,
    {
        self.send(self.http.delete(self.url(path))).await
    }

    async fn get_bytes(&self, path: &str, query: &[(&str, String)]) -> Result<Vec<u8>> {
        let response = self
            .with_auth(self.http.get(self.url(path)).query(query))
            .send()
            .await
            .context("request failed")?;

        let status = response.status();
        let body = response
            .bytes()
            .await
            .context("failed to read response body")?;
        if !status.is_success() {
            bail!(
                "server returned {status}: {}",
                String::from_utf8_lossy(&body)
            );
        }

        Ok(body.to_vec())
    }

    fn url(&self, path: &str) -> String {
        format!("{}{}", self.base_url, path)
    }

    fn with_auth(&self, request: reqwest::RequestBuilder) -> reqwest::RequestBuilder {
        if self.api_key.is_empty() {
            request
        } else {
            request.header("X-API-Key", &self.api_key)
        }
    }

    async fn send<T>(&self, request: reqwest::RequestBuilder) -> Result<T>
    where
        T: for<'de> Deserialize<'de>,
    {
        let response = self
            .with_auth(request)
            .send()
            .await
            .context("request failed")?;
        let status = response.status();
        let body = response
            .text()
            .await
            .context("failed to read response body")?;

        if !status.is_success() {
            bail!("server returned {status}: {body}");
        }

        serde_json::from_str(&body).context("failed to parse response JSON")
    }
}

#[tokio::main]
async fn main() -> Result<()> {
    let cli = Cli::parse();
    let client = ApiClient::new(cli.base_url, cli.api_key);

    match cli.command {
        Commands::Admin(command) => handle_admin(&client, command).await?,
        Commands::Transactions(command) => handle_transactions(&client, command).await?,
        Commands::Settlements(command) => handle_settlements(&client, command).await?,
        Commands::Completions { shell } => print_completions(&shell)?,
    }

    Ok(())
}

async fn handle_admin(client: &ApiClient, command: AdminCommands) -> Result<()> {
    match command {
        AdminCommands::Reconciliation(command) => handle_reconciliation(client, command).await,
        AdminCommands::Locks(command) => handle_locks(client, command).await,
        AdminCommands::Quotas(command) => handle_quotas(client, command).await,
    }
}

async fn handle_locks(client: &ApiClient, command: LockCommands) -> Result<()> {
    match command {
        LockCommands::List { json } => {
            let response: ListLocksResponse = client.get("/admin/locks").await?;
            println!("{}", output::render(&response, json, format_locks_table)?);
        }
    }

    Ok(())
}

async fn handle_quotas(client: &ApiClient, command: QuotaCommands) -> Result<()> {
    match command {
        QuotaCommands::List { json } => {
            let response: Vec<TenantQuotaView> = client.get("/admin/quotas").await?;
            println!(
                "{}",
                Formatter::format_json_output(&response, OutputFormat::from_json_flag(json))?
            );
        }
        QuotaCommands::Get { tenant_id, json } => {
            let response: TenantQuotaView =
                client.get(&format!("/admin/quotas/{tenant_id}")).await?;
            println!(
                "{}",
                Formatter::format_json_output(&response, OutputFormat::from_json_flag(json))?
            );
        }
        QuotaCommands::Set {
            tenant_id,
            limit,
            limit_flag,
            json: as_json,
        } => {
            let Some(limit) = limit.or(limit_flag) else {
                bail!("quota limit is required");
            };

            if limit == 0 {
                bail!("quota limit must be positive");
            }

            let response: serde_json::Value = client
                .put_json(
                    &format!("/admin/quotas/{tenant_id}"),
                    json!({ "custom_limit": limit }),
                )
                .await?;
            println!(
                "{}",
                Formatter::format_json_output(&response, OutputFormat::from_json_flag(as_json))?
            );
        }
        QuotaCommands::Reset { tenant_id, json } => {
            let response: serde_json::Value = client
                .delete(&format!("/admin/quotas/{tenant_id}/reset"))
                .await?;
            println!(
                "{}",
                Formatter::format_json_output(&response, OutputFormat::from_json_flag(json))?
            );
        }
    }

    Ok(())
}

async fn handle_reconciliation(client: &ApiClient, command: ReconciliationCommands) -> Result<()> {
    match command {
        ReconciliationCommands::Reports {
            limit,
            offset,
            json,
        } => {
            let response: ListReportsResponse = client
                .get(&format!(
                    "/admin/reconciliation/reports?limit={limit}&offset={offset}"
                ))
                .await?;
            println!("{}", output::render(&response, json, format_reports_table)?);
        }
        ReconciliationCommands::Report { report_id, json } => {
            let response: ReportDetailResponse = client
                .get(&format!("/admin/reconciliation/reports/{report_id}"))
                .await?;
            println!("{}", output::render(&response, json, format_report_table)?);
        }
        ReconciliationCommands::Run {
            account,
            period_hours,
            json,
        } => {
            let response: RunResponse = client
                .post_json(
                    "/admin/reconciliation/run",
                    &RunRequest {
                        account: &account,
                        period_hours: Some(period_hours),
                    },
                )
                .await?;
            println!("{}", output::render(&response, json, format_run_table)?);
        }
    }

    Ok(())
}

async fn handle_transactions(client: &ApiClient, command: TransactionsCommands) -> Result<()> {
    match command {
        TransactionsCommands::Export {
            format,
            from,
            to,
            status,
            asset_code,
            output,
        } => {
            let mut query = vec![("format", format)];
            push_optional_query(&mut query, "from", from);
            push_optional_query(&mut query, "to", to);
            push_optional_query(&mut query, "status", status);
            push_optional_query(&mut query, "asset_code", asset_code);

            let bytes = client.get_bytes("/export", &query).await?;
            if let Some(path) = output {
                std::fs::write(&path, bytes)?;
                println!("Exported to {path}");
            } else {
                println!("{}", String::from_utf8(bytes)?);
            }
        }
    }

    Ok(())
}

async fn handle_settlements(client: &ApiClient, command: SettlementsCommands) -> Result<()> {
    match command {
        SettlementsCommands::List {
            cursor,
            limit,
            direction,
            format,
        } => {
            let mut query = vec![("limit", limit.to_string()), ("direction", direction)];
            push_optional_query(&mut query, "cursor", cursor);
            let query = query
                .iter()
                .map(|(key, value)| format!("{key}={value}"))
                .collect::<Vec<_>>()
                .join("&");
            let response: serde_json::Value = client.get(&format!("/settlements?{query}")).await?;
            println!(
                "{}",
                Formatter::format_json_output(&response, OutputFormat::from_str(&format))?
            );
        }
        SettlementsCommands::Get {
            settlement_id,
            format,
        } => {
            let response: serde_json::Value =
                client.get(&format!("/settlements/{settlement_id}")).await?;
            println!(
                "{}",
                Formatter::format_json_output(&response, OutputFormat::from_str(&format))?
            );
        }
    }

    Ok(())
}

fn push_optional_query(
    query: &mut Vec<(&'static str, String)>,
    key: &'static str,
    value: Option<String>,
) {
    if let Some(value) = value {
        query.push((key, value));
    }
}

fn print_completions(shell: &str) -> Result<()> {
    match shell {
        "bash" => println!("_synapse() {{\n    :\n}}\ncomplete -F _synapse synapse"),
        "zsh" => println!("#compdef synapse\ncompdef _synapse synapse\n_synapse() {{\n    :\n}}"),
        "fish" => println!("complete -c synapse -f"),
        _ => bail!("Unsupported shell: {shell}"),
    }

    Ok(())
}

fn format_reports_table(response: &ListReportsResponse) -> String {
    let mut lines = vec![format!(
        "Reports: {} total (showing {} from offset {}, limit {})",
        response.total,
        response.reports.len(),
        response.offset,
        response.limit
    )];

    if response.reports.is_empty() {
        lines.push("No reconciliation reports found".to_string());
        return lines.join("\n");
    }

    lines.push(
        "ID | Generated | Period Start | Period End | DB | Chain | Discrepancies".to_string(),
    );
    lines.push(
        "-- | --------- | ------------ | ---------- | -- | ----- | -------------".to_string(),
    );

    for report in &response.reports {
        lines.push(format!(
            "{} | {} | {} | {} | {} | {} | {}",
            report.id,
            report.generated_at,
            report.period_start,
            report.period_end,
            report.total_db_transactions,
            report.total_chain_payments,
            yes_no(report.has_discrepancies)
        ));
    }

    lines.join("\n")
}

fn format_report_table(report: &ReportDetailResponse) -> String {
    let mut lines = vec![
        format!("Report ID: {}", report.id),
        format!("Generated: {}", report.generated_at),
        format!("Period: {} to {}", report.period_start, report.period_end),
        String::new(),
        "Summary:".to_string(),
        format!(
            "  Database transactions: {}",
            report.summary.total_db_transactions
        ),
        format!("  Chain payments: {}", report.summary.total_chain_payments),
        format!(
            "  Missing on chain: {}",
            report.summary.missing_on_chain_count
        ),
        format!(
            "  Orphaned payments: {}",
            report.summary.orphaned_payments_count
        ),
        format!(
            "  Amount mismatches: {}",
            report.summary.amount_mismatches_count
        ),
        format!(
            "  Has discrepancies: {}",
            yes_no(report.summary.has_discrepancies)
        ),
    ];

    if report.missing_on_chain.is_empty()
        && report.orphaned_payments.is_empty()
        && report.amount_mismatches.is_empty()
    {
        lines.push(String::new());
        lines.push("No discrepancies found".to_string());
    }

    lines.join("\n")
}

fn format_run_table(response: &RunResponse) -> String {
    let report = &response.report;
    [
        response.message.clone(),
        String::new(),
        format!("Report ID: {}", report.id),
        format!("Generated: {}", report.generated_at),
        format!("Period: {} to {}", report.period_start, report.period_end),
        String::new(),
        "Summary:".to_string(),
        format!("  Database transactions: {}", report.total_db_transactions),
        format!("  Chain payments: {}", report.total_chain_payments),
        format!("  Missing on chain: {}", report.missing_on_chain_count),
        format!("  Orphaned payments: {}", report.orphaned_payments_count),
        format!("  Amount mismatches: {}", report.amount_mismatches_count),
        format!("  Has discrepancies: {}", yes_no(report.has_discrepancies)),
    ]
    .join("\n")
}

fn format_locks_table(response: &ListLocksResponse) -> String {
    let mut lines = vec![format!(
        "Active locks: {} total ({} overdue)",
        response.total, response.overdue
    )];

    if response.active_locks.is_empty() {
        lines.push("No active locks found".to_string());
        return lines.join("\n");
    }

    lines.push("Resource | Token | Acquired At | TTL | Expected Duration | Overdue".to_string());
    lines.push("-------- | ----- | ----------- | --- | ----------------- | -------".to_string());

    for lock in &response.active_locks {
        lines.push(format!(
            "{} | {} | {} | {} | {} | {}",
            lock.resource,
            lock.token,
            lock.acquired_at,
            lock.ttl_secs,
            lock.expected_duration_secs,
            yes_no(lock.overdue)
        ));
    }

    lines.join("\n")
}

fn yes_no(value: bool) -> &'static str {
    if value {
        "yes"
    } else {
        "no"
    }
}
