use anyhow::{bail, Context, Result};
use clap::{Parser, Subcommand};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

mod output;

#[derive(Parser, Debug)]
#[command(
    name = "synapse",
    version,
    about = "Synapse admin CLI",
    long_about = "Manage Synapse admin reconciliation commands.\n\nUse the nested reconciliation subcommands to list stored reports, inspect a single report, or run a fresh reconciliation against the API.",
    arg_required_else_help = true
)]
struct Cli {
    /// Base URL of the Synapse API.
    #[arg(
        long,
        value_name = "URL",
        default_value = "http://127.0.0.1:3000"
    )]
    base_url: String,

    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand, Debug)]
enum Commands {
    /// Admin operations exposed by the Synapse API.
    #[command(
        about = "Admin operations",
        long_about = "Admin operations exposed by the Synapse API."
    )]
    Admin(AdminCommands),
}

#[derive(Subcommand, Debug)]
enum AdminCommands {
    /// Reconciliation reports and runs.
    #[command(
        about = "Reconciliation reports",
        long_about = "List, inspect, or run reconciliation reports through the admin API."
    )]
    Reconciliation(ReconciliationCommands),
}

#[derive(Subcommand, Debug)]
enum ReconciliationCommands {
    #[command(
        about = "List reconciliation reports",
        long_about = "List reconciliation reports generated by the admin API.\n\nRequired flags: none.\nOptional flags:\n  --limit <LIMIT>   Maximum number of reports to return (default: 20).\n  --offset <OFFSET>  Number of reports to skip before returning results (default: 0).\n  --json            Print the raw API response as JSON."
    )]
    Reports {
        /// Maximum number of reports to return.
        #[arg(long, value_name = "LIMIT", default_value_t = 20)]
        limit: u32,

        /// Number of reports to skip before returning results.
        #[arg(long, value_name = "OFFSET", default_value_t = 0)]
        offset: u32,

        /// Print the raw API response as JSON.
        #[arg(long)]
        json: bool,
    },

    #[command(
        about = "Show a reconciliation report",
        long_about = "Fetch one reconciliation report by UUID and print the full response body.\n\nRequired flags:\n  <REPORT_ID>       UUID of the report to fetch.\nOptional flags:\n  --json            Print the raw API response as JSON."
    )]
    Report {
        /// UUID of the reconciliation report to fetch.
        #[arg(value_name = "REPORT_ID")]
        report_id: Uuid,

        /// Print the raw API response as JSON.
        #[arg(long)]
        json: bool,
    },

    #[command(
        about = "Run a reconciliation report",
        long_about = "Run a reconciliation pass for one Stellar account and persist the result.\n\nRequired flags:\n  --account <ACCOUNT>      Stellar account to reconcile.\nOptional flags:\n  --period-hours <HOURS>   Hours of history to include (default: 24).\n  --json                   Print the raw API response as JSON."
    )]
    Run {
        /// Stellar account to reconcile.
        #[arg(long, value_name = "ACCOUNT")]
        account: String,

        /// Hours of history to include.
        #[arg(long, value_name = "HOURS")]
        period_hours: Option<u32>,

        /// Print the raw API response as JSON.
        #[arg(long)]
        json: bool,
    },
}

#[derive(Debug, Deserialize, Serialize)]
struct ListReportsResponse {
    reports: Vec<ReportSummary>,
    total: i64,
    limit: i32,
    offset: i32,
}

#[derive(Debug, Deserialize, Serialize)]
struct ReportSummary {
    id: Uuid,
    generated_at: String,
    period_start: String,
    period_end: String,
    total_db_transactions: i32,
    total_chain_payments: i32,
    missing_on_chain_count: i32,
    orphaned_payments_count: i32,
    amount_mismatches_count: i32,
    has_discrepancies: bool,
}

#[derive(Debug, Deserialize, Serialize)]
struct ReportDetailResponse {
    id: Uuid,
    generated_at: String,
    period_start: String,
    period_end: String,
    summary: ReportDetailSummary,
    missing_on_chain: Vec<MissingTransactionOutput>,
    orphaned_payments: Vec<OrphanedPaymentOutput>,
    amount_mismatches: Vec<AmountMismatchOutput>,
}

#[derive(Debug, Deserialize, Serialize)]
struct ReportDetailSummary {
    total_db_transactions: usize,
    total_chain_payments: usize,
    missing_on_chain_count: i32,
    orphaned_payments_count: i32,
    amount_mismatches_count: i32,
    has_discrepancies: bool,
}

#[derive(Debug, Deserialize, Serialize)]
struct MissingTransactionOutput {
    id: Uuid,
    stellar_account: String,
    amount: String,
    asset_code: String,
    memo: Option<String>,
    created_at: String,
}

#[derive(Debug, Deserialize, Serialize)]
struct OrphanedPaymentOutput {
    payment_id: String,
    from: String,
    to: String,
    amount: String,
    asset_code: String,
    memo: Option<String>,
}

#[derive(Debug, Deserialize, Serialize)]
struct AmountMismatchOutput {
    transaction_id: Uuid,
    payment_id: String,
    db_amount: String,
    chain_amount: String,
    memo: Option<String>,
}

#[derive(Debug, Deserialize, Serialize)]
struct RunResponse {
    message: String,
    report: ReportSummary,
}

#[derive(Debug, Serialize)]
struct RunRequest<'a> {
    account: &'a str,
    period_hours: Option<u32>,
}

#[tokio::main]
async fn main() -> Result<()> {
    let cli = Cli::parse();
    let client = reqwest::Client::new();
    let base_url = cli.base_url.trim_end_matches('/').to_string();

    match cli.command {
        Commands::Admin(admin) => match admin {
            AdminCommands::Reconciliation(command) => {
                handle_reconciliation(&client, &base_url, command).await?
            }
        },
    }

    Ok(())
}

async fn handle_reconciliation(
    client: &reqwest::Client,
    base_url: &str,
    command: ReconciliationCommands,
) -> Result<()> {
    match command {
        ReconciliationCommands::Reports {
            limit,
            offset,
            json,
        } => {
            let url = format!("{base_url}/admin/reconciliation/reports?limit={limit}&offset={offset}");
            let response = send_json_request::<ListReportsResponse>(client.get(url)).await?;
            println!("{}", output::render(&response, json, format_reports_table)?);
        }
        ReconciliationCommands::Report { report_id, json } => {
            let url = format!("{base_url}/admin/reconciliation/reports/{report_id}");
            let response = send_json_request::<ReportDetailResponse>(client.get(url)).await?;
            println!("{}", output::render(&response, json, format_report_table)?);
        }
        ReconciliationCommands::Run {
            account,
            period_hours,
            json,
        } => {
            let url = format!("{base_url}/admin/reconciliation/run");
            let response = send_json_request::<RunResponse>(
                client.post(url).json(&RunRequest {
                    account: &account,
                    period_hours,
                }),
            )
            .await?;
            println!("{}", output::render(&response, json, format_run_table)?);
        }
    }

    Ok(())
}

async fn send_json_request<T>(request: reqwest::RequestBuilder) -> Result<T>
where
    T: for<'de> Deserialize<'de>,
{
    let response = request.send().await.context("request failed")?;
    let status = response.status();
    let body = response.text().await.context("failed to read response body")?;

    if !status.is_success() {
        bail!("server returned {status}: {body}");
    }

    serde_json::from_str(&body).context("failed to parse response JSON")
}

fn format_reports_table(response: &ListReportsResponse) -> String {
    let mut lines = vec![format!(
        "Reports: {} total (showing {} from offset {}, limit {})",
        response.total,
        response.reports.len(),
        response.offset,
        response.limit
    )];

    if response.reports.is_empty() {
        lines.push("No reconciliation reports found".to_string());
        return lines.join("\n");
    }

    lines.push(
        "ID | Generated | Period Start | Period End | DB | Chain | Discrepancies".to_string(),
    );
    lines.push(
        "-- | --------- | ------------ | ---------- | -- | ----- | -------------".to_string(),
    );

    for report in &response.reports {
        lines.push(format!(
            "{} | {} | {} | {} | {} | {} | {}",
            report.id,
            report.generated_at,
            report.period_start,
            report.period_end,
            report.total_db_transactions,
            report.total_chain_payments,
            yes_no(report.has_discrepancies)
        ));
    }

    lines.join("\n")
}

fn format_report_table(report: &ReportDetailResponse) -> String {
    let mut lines = vec![
        format!("Report ID: {}", report.id),
        format!("Generated: {}", report.generated_at),
        format!("Period: {} to {}", report.period_start, report.period_end),
        String::new(),
        "Summary:".to_string(),
        format!("  Database transactions: {}", report.summary.total_db_transactions),
        format!("  Chain payments: {}", report.summary.total_chain_payments),
        format!("  Missing on chain: {}", report.summary.missing_on_chain_count),
        format!("  Orphaned payments: {}", report.summary.orphaned_payments_count),
        format!("  Amount mismatches: {}", report.summary.amount_mismatches_count),
        format!("  Has discrepancies: {}", yes_no(report.summary.has_discrepancies)),
    ];

    if report.missing_on_chain.is_empty()
        && report.orphaned_payments.is_empty()
        && report.amount_mismatches.is_empty()
    {
        lines.push(String::new());
        lines.push("No discrepancies found".to_string());
    }

    lines.join("\n")
}

fn yes_no(value: bool) -> &'static str {
    if value { "yes" } else { "no" }
}

fn format_run_table(response: &RunResponse) -> String {
    let report = &response.report;
    [
        response.message.clone(),
        String::new(),
        format!("Report ID: {}", report.id),
        format!("Generated: {}", report.generated_at),
        format!("Period: {} to {}", report.period_start, report.period_end),
        String::new(),
        "Summary:".to_string(),
        format!("  Database transactions: {}", report.total_db_transactions),
        format!("  Chain payments: {}", report.total_chain_payments),
        format!("  Missing on chain: {}", report.missing_on_chain_count),
        format!("  Orphaned payments: {}", report.orphaned_payments_count),
        format!("  Amount mismatches: {}", report.amount_mismatches_count),
        format!("  Has discrepancies: {}", yes_no(report.has_discrepancies)),
    ]
    .join("\n")
}
